# docker compose -f docker-compose-postgres.yml up
# docker compose -f docker-compose-postgres.yml down

services:
  postgres:
    image: postgres:15
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Seoul
      LANG: en_US.utf8
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
